import type { WeeklyReport } from "./types.js";

export function renderMarkdown(report: WeeklyReport): string {
  const lines = [
    `# AI Week in Review`,
    `> ${report.startDate} to ${report.endDate}`,
    "",
    "## Summary",
    `- **${report.totalInteractions}** AI interactions`,
    `- **${report.totalMinutes}** minutes with AI`,
    "",
  ];
  if (report.toolBreakdown.length > 0) {
    lines.push("## Tools Used");
    for (const t of report.toolBreakdown) {
      const bar = "=".repeat(Math.round(t.percentage / 10));
      lines.push(`- ${t.tool}: ${t.count} uses (${t.percentage}%) ${bar}`);
    }
    lines.push("");
  }
  if (report.taskBreakdown.length > 0) {
    lines.push("## Task Types");
    for (const t of report.taskBreakdown) lines.push(`- ${t.task}: ${t.count} (${t.percentage}%)`);
    lines.push("");
  }
  lines.push(
    "## Tip of the Week",
    report.tip,
    "",
    "---",
    "*Generated by [@maiife/weekly-ai-report](https://github.com/maiife/toolkit)*"
  );
  return lines.join("\n");
}

export function renderTable(report: WeeklyReport): string {
  const lines = [
    `\nAI Week in Review (${report.startDate} to ${report.endDate})\n`,
    `  ${report.totalInteractions} interactions - ${report.totalMinutes} minutes\n`,
  ];
  if (report.toolBreakdown.length > 0) {
    lines.push("  Tools:");
    for (const t of report.toolBreakdown)
      lines.push(`    ${t.tool.padEnd(15)} ${t.count} uses (${t.percentage}%) - ${t.minutes}min`);
  }
  if (report.taskBreakdown.length > 0) {
    lines.push("\n  Tasks:");
    for (const t of report.taskBreakdown)
      lines.push(`    ${t.task.padEnd(15)} ${t.count} (${t.percentage}%)`);
  }
  lines.push(`\n  Tip: ${report.tip}\n`);
  return lines.join("\n");
}
